all: exploit1 exploit2 exploit3

exploit1: exploit1.c
	gcc -o exploit1 exploit1.c -I.
	
exploit2: exploit2.c
	gcc -o exploit2 -m32 exploit2.c -I.

exploit3: exploit3.c
	gcc -o exploit3 exploit3.c -I.